# Generated by Django 4.1.2 on 2022-11-02 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.BooleanField(default=False, verbose_name='09:00 AM')),
                ('time2', models.BooleanField(default=False, verbose_name='10:00 AM')),
                ('time3', models.BooleanField(default=False, verbose_name='11:00 AM')),
                ('time4', models.BooleanField(default=False, verbose_name='12:00 AM')),
                ('time5', models.BooleanField(default=False, verbose_name='02:00 PM')),
                ('time6', models.BooleanField(default=False, verbose_name='03:00 PM')),
                ('time7', models.BooleanField(default=False, verbose_name='04:00 PM')),
                ('time8', models.BooleanField(default=False, verbose_name='05:00 PM')),
                ('time9', models.BooleanField(default=False, verbose_name='07:00 PM')),
                ('time10', models.BooleanField(default=False, verbose_name='08:00 PM')),
                ('time11', models.BooleanField(default=False, verbose_name='09:00 PM')),
                ('time12', models.BooleanField(default=False, verbose_name='10:00 PM')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'barber',
                'verbose_name_plural': 'barbers',
            },
        ),
    ]
