# Generated by Django 4.1.2 on 2022-11-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbermodel',
            name='user',
        ),
    ]
